"""Placeholder onboard 'sensor' defect detector.

Classical CV heuristics tuned to the synthetic wall textures generated by
scene/make_textures.py (crack = thin dark jagged line, rust = brown blobs,
leak = dark vertical wedge). This stands in for the trained YOLOv8-seg
model from the week-1 plan, which needs a real annotated dataset — this
version has zero network/training dependency so it's guaranteed to work
today. Swap `detect_defects` for a real model call later without touching
sim.py or run_demo.py.
"""
import cv2
import numpy as np

# Fraction-of-frame crop where the target wall consistently sits, given the
# fixed camera framing (drone always looks dead-center at the wall). Keeps
# the floor/sky/neighboring walls out of consideration. Tuned for the
# gym-pybullet-drones onboard FPV camera framing in sim_gpd.py.
ROI_FRAC = (0.18, 0.10, 0.78, 0.82)  # x0, y0, x1, y1 as fractions of W, H


def _roi_bounds(w, h):
    x0f, y0f, x1f, y1f = ROI_FRAC
    return int(x0f * w), int(y0f * h), int(x1f * w), int(y1f * h)


def _detect_dark_regions(gray_roi):
    """Crack and leak are both darker than the wall base color, but differ
    in shape: crack is a sparse, thin, tall scribble (low fill extent);
    leak is a solid, near-full-height wedge (high fill extent). Rust blobs
    are also dark enough to show up here, so they're excluded by requiring
    leak candidates to span most of the ROI height, well above any single
    rust blob's diameter."""
    median = float(np.median(gray_roi))
    thresh = max(0, median - 25)
    _, mask = cv2.threshold(gray_roi, thresh, 255, cv2.THRESH_BINARY_INV)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, np.ones((9, 9), np.uint8), iterations=2)
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    roi_h = gray_roi.shape[0]
    results = []
    for c in contours:
        area = cv2.contourArea(c)
        if area < 150:
            continue
        x, y, w, h = cv2.boundingRect(c)
        extent = area / max(w * h, 1)
        aspect = h / max(w, 1)

        if extent < 0.30 and aspect > 1.3 and h > 60:
            confidence = float(np.clip(h / 200.0, 0.3, 0.95))
            results.append({"bbox": (x, y, w, h), "label": "crack", "confidence": confidence})
        elif extent > 0.35 and h > 0.55 * roi_h:
            confidence = float(np.clip(extent, 0.3, 0.95))
            results.append({"bbox": (x, y, w, h), "label": "leak", "confidence": confidence})
    return results


def _detect_rust(bgr_roi):
    hsv = cv2.cvtColor(bgr_roi, cv2.COLOR_BGR2HSV)
    mask = cv2.inRange(hsv, (0, 90, 35), (25, 255, 210))
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, np.ones((5, 5), np.uint8), iterations=2)
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    dets = []
    for c in contours:
        area = cv2.contourArea(c)
        if area < 120:
            continue
        x, y, w, h = cv2.boundingRect(c)
        confidence = float(np.clip(area / 900.0, 0.35, 0.95))
        dets.append({"bbox": (x, y, w, h), "label": "rust", "confidence": confidence})
    return dets


def detect_defects(bgr_frame):
    """Returns a list of {bbox: (x,y,w,h) in full-frame coords, label, confidence}."""
    h, w = bgr_frame.shape[:2]
    x0, y0, x1, y1 = _roi_bounds(w, h)
    roi_bgr = bgr_frame[y0:y1, x0:x1]
    roi_gray = cv2.cvtColor(roi_bgr, cv2.COLOR_BGR2GRAY)

    detections = []
    detections.extend(_detect_dark_regions(roi_gray))
    detections.extend(_detect_rust(roi_bgr))

    # offset ROI-local boxes back into full-frame coordinates
    for d in detections:
        bx, by, bw, bh = d["bbox"]
        d["bbox"] = (bx + x0, by + y0, bw, bh)

    return detections


if __name__ == "__main__":
    import os

    cap_dir = os.path.join(os.path.dirname(__file__), "captures")
    for fname in sorted(os.listdir(cap_dir)):
        if not (fname.startswith("frame_") or fname.startswith("gpd_frame_")):
            continue
        img = cv2.imread(os.path.join(cap_dir, fname))
        dets = detect_defects(img)
        labels = [f"{d['label']}({d['confidence']:.2f})" for d in dets]
        print(f"{fname}: {labels if labels else 'clean / no detection'}")
